"""
tools/make_reference.py —— 自动生成 TwoPunctures 参考解 reference_u.npz
=======================================================================

在**服务器(Linux,需 gcc + GSL)**上运行。完成四步:
    1. 由论文算例(与 config.py 一致)生成 TwoPunctures 参数文件 par
    2. 编译 TwoPuncturesC(若尚未编译)与本目录的 dump_psi_grid.c
    3. 运行 dump_psi_grid 输出 ψ 网格文本
    4. 换算 u = ψ − 1 − Σ m/(2r) 并保存 reference_u.npz

支持两种网格模式:
    [均匀模式] (--grid-n N): 全空间 [-R,R]^3 均匀 N³ 网格
    [自适应模式] (默认): 奇点附近高分辨率,远离奇点低分辨率,
        在不增加总点数的前提下大幅提高峰值处参考解精度

用法:
    # 等质量无自旋基准算例(默认自适应网格)
    python make_reference.py --case base

    # 使用均匀网格(兼容旧版)
    python make_reference.py --case base --mode uniform --grid-n 161

    # 不等质量自旋(论文最高配置)
    python make_reference.py --case uneq_spin

    # 自定义自适应参数
    python make_reference.py --case base --focus-n 201 --outer-n 81

参数:
    --case       : base / spin_eq / uneq_nospin / uneq_spin(默认 base)
    --mode       : adaptive(默认) / uniform
    --tp-dir     : TwoPuncturesC 源码目录(默认 ../../TwoPuncturesC)
    --grid-n     : [uniform模式] 每方向网格点数(默认 61)
    --focus-n    : [adaptive模式] 奇点附近高分辨率块每方向点数(默认 201)
    --outer-n    : [adaptive模式] 外层低分辨率块每方向点数(默认 61)
    --focus-half : [adaptive模式] 高分辨率块半边长(默认 3.0)
    --R          : 网格半边长(默认 30,与 PINN 计算域 R_max 一致)
    --work-dir   : 工作目录(默认 ./tp_work,存放中间文件)
    --out        : 输出 npz 路径(默认 reference_u.npz)

输出:
    reference_u.npz 含 x_ref (M,3) 与 u_ref (M,),可直接传给 main.py --reference。

自适应网格设计:
    奇点附近解变化剧烈(~1/r 发散),均匀网格在近奇点区域分辨率不足
    (即使 201³ 仍有锯齿)。自适应模式用三个嵌套网格块:
      - 内层高分辨率块: 围绕 x=±xp, [-focus_half, focus_half]³, focus_n³ 点
      - 外层低分辨率块: [-R, R]³, outer_n³ 点
    内外层重叠区域自动去重(保留高分辨率块的结果)。
"""

import argparse
import os
import subprocess
import sys
import itertools

import numpy as np

# 让本脚本能 import 上级目录的 config.py
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import BBHConfig  # noqa: E402


# ----------------------------------------------------------------------
# 1. 生成 TwoPunctures 参数文件(与 config.BBHConfig 映射)
# ----------------------------------------------------------------------
def write_parfile(bb: BBHConfig, path: str, npoints: int = 60):
    """把论文物理参数映射为 TwoPunctures par 文件。

    映射关系(TwoPuncturesC 源码确认):
        - 奇点位置:x=±par_b, 故 par_b = bb.x_plus[0]
        - 裸质量:  par_m_plus / par_m_minus = bb.m_plus / bb.m_minus
        - 动量:    par_P_plus{1,2,3} = P 的三个分量(1=x, 2=y, 3=z)
        - 自旋:    par_S_plus{1,2,3} = S 的三个分量
        - give_bare_mass=1:直接给裸质量而非目标 ADM 质量(论文 m 即裸质量)

    Args:
        bb     : BBHConfig(论文物理参数)
        path   : par 文件输出路径
        npoints: 谱展开点数(npoints_A/B/phi,越大越准,默认 60)
    """
    m_p, m_m = bb.m_plus, bb.m_minus
    P_p = bb.P_plus; P_m = bb.P_minus
    S_p = bb.S_plus; S_m = bb.S_minus
    xp = bb.x_plus[0]                                   # 奇点在 x=±xp

    par = f"""# TwoPunctures par file generated by make_reference.py
# case: m+={m_p}, m-={m_m}, x=+-{xp}, P+=({P_p[0]},{P_p[1]},{P_p[2]}), P-=({P_m[0]},{P_m[1]},{P_m[2]}), S+=({S_p[0]},{S_p[1]},{S_p[2]}), S-=({S_m[0]},{S_m[1]},{S_m[2]})
par_b={xp}
par_m_plus={m_p}
par_m_minus={m_m}
target_M_plus=0.5
target_M_minus=0.5
par_P_plus1={P_p[0]}
par_P_plus2={P_p[1]}
par_P_plus3={P_p[2]}
par_P_minus1={P_m[0]}
par_P_minus2={P_m[1]}
par_P_minus3={P_m[2]}
par_S_plus1={S_p[0]}
par_S_plus2={S_p[1]}
par_S_plus3={S_p[2]}
par_S_minus1={S_m[0]}
par_S_minus2={S_m[1]}
par_S_minus3={S_m[2]}
center_offset1=0.
center_offset2=0.
center_offset3=0.
give_bare_mass=1
npoints_A={npoints}
npoints_B={npoints}
npoints_phi={npoints}
Newton_tol=1.0000000000000000e-10
Newton_maxit=5
TP_epsilon=0.
TP_Tiny=0.
TP_Extend_Radius=0.
adm_tol=1.0000000000000000e-10
solve_momentum_constraint=0
use_external_initial_guess=0
do_residuum_debug_output=0
do_initial_debug_output=0
do_solution_file_output=0
do_bam_file_output=0
grid_setup_method=0
initial_lapse=2
initial_lapse_psi_exponent=-2.0000000000000000e+00
conformal_state=1
swap_xz=0
multiply_old_lapse=0
verbose=1
"""
    with open(path, "w") as f:
        f.write(par)
    print(f"[1/4] 已生成 par 文件: {path}")


# ----------------------------------------------------------------------
# 2. 编译 TwoPuncturesC 与 dump_psi_grid
# ----------------------------------------------------------------------
def compile_twopunctures(tp_dir: str, work_dir: str) -> str:
    """编译 TwoPuncturesC(make)与 dump_psi_grid.c。

    Args:
        tp_dir  : TwoPuncturesC 源码目录
        work_dir: 工作目录(存放 dump_psi_grid 可执行文件)

    Returns:
        dump_exe: dump_psi_grid 可执行文件路径
    """
    # 2a. 编译 TwoPuncturesC(生成 libTwoPunctures.a / .so)
    lib = os.path.join(tp_dir, "lib", "libTwoPunctures.a")
    if not os.path.exists(lib):
        print("[2/4] 编译 TwoPuncturesC(make, 单线程)...")
        r = subprocess.run(
            ["make", "-C", tp_dir,
             "CFLAGS=-std=c99 -fPIC -pedantic -O3 $(shell gsl-config --cflags)"],
            capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stdout[-3000:])
            print(r.stderr[-3000:])
            sys.exit(f"TwoPuncturesC 编译失败。需要 gcc + GSL(sudo apt install gcc libgsl-dev)")
    else:
        print(f"[2/4] TwoPuncturesC 已编译: {lib}")

    # 2b. 编译 dump_psi_grid.c(链接 libTwoPunctures + GSL;单线程,无 -fopenmp)
    dump_exe = os.path.join(work_dir, "dump_psi_grid")
    src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dump_psi_grid.c")
    need_rebuild = (not os.path.exists(dump_exe)
                    or os.path.getmtime(src) > os.path.getmtime(dump_exe))
    if need_rebuild:
        print("[2/4] 编译 dump_psi_grid.c...")
        cmd = ["gcc", "-O2", "-std=c99",
               "-I", os.path.join(tp_dir, "include"),
               "-I", os.path.join(tp_dir, "src"),
               src, lib,
               "-lgsl", "-lgslcblas", "-lm",
               "-o", dump_exe]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stdout[-3000:]); print(r.stderr[-3000:])
            sys.exit("dump_psi_grid 编译失败")
    else:
        print(f"[2/4] dump_psi_grid 已编译: {dump_exe}")
    return dump_exe


def run_streaming(cmd: list, fail_msg: str):
    """运行子进程并实时转发其输出(避免阻塞式 capture_output 的"卡死"错觉)。

    Args:
        cmd     : 命令行列表
        fail_msg: 失败时打印的提示
    """
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1)
    for line in proc.stdout:
        print("  " + line, end="", flush=True)
    proc.wait()
    if proc.returncode != 0:
        sys.exit(fail_msg)


# ----------------------------------------------------------------------
# 3a. 均匀模式:生成网格块参数
# ----------------------------------------------------------------------
def uniform_blocks(R: float, N: int):
    """生成均匀网格块(整个 [-R,R]^3 一个块)。

    Returns:
        blocks: list of (xmin, xmax, ymin, ymax, zmin, zmax, nx, ny, nz)
    """
    return [(-R, R, -R, R, -R, R, N, N, N)]


# ----------------------------------------------------------------------
# 3b. 自适应模式:生成嵌套网格块参数
# ----------------------------------------------------------------------
def adaptive_blocks(R: float, xp: float, focus_half: float,
                    focus_n: int, outer_n: int):
    """生成自适应网格块:奇点附近高分辨率,外层低分辨率。

    策略:
        - 两个高分辨率内层块:围绕 x=±xp, [±xp-focus_half, ±xp+focus_half]³,
          每方向 focus_n 点
        - 一个低分辨率外层块: [-R,R]³, 每方向 outer_n 点
        - 输出时内层块优先,重叠区域以内层高分辨率为准

    Args:
        R          : 外层半边长
        xp         : 奇点 x 坐标(绝对值)
        focus_half : 内层块半边长
        focus_n    : 内层块每方向点数
        outer_n    : 外层块每方向点数

    Returns:
        blocks: list of (xmin, xmax, ymin, ymax, zmin, zmax, nx, ny, nz),
                内层块在前(优先),外层块在后
    """
    blocks = []
    # 两个高分辨率内层块(围绕每个奇点)
    for xc in [xp, -xp]:
        blocks.append((
            xc - focus_half, xc + focus_half,
            -focus_half, focus_half,
            -focus_half, focus_half,
            focus_n, focus_n, focus_n,
        ))
    # 外层低分辨率块
    blocks.append((-R, R, -R, R, -R, R, outer_n, outer_n, outer_n))
    return blocks


# ----------------------------------------------------------------------
# 3. 运行 dump_psi_grid + 4. 换算保存
# ----------------------------------------------------------------------
def main():
    p = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--case", default="base",
                   choices=["base", "spin_eq", "uneq_nospin", "uneq_spin"])
    p.add_argument("--mode", default="adaptive",
                   choices=["adaptive", "uniform"],
                   help="网格模式: adaptive=峰值加密(默认), uniform=全空间均匀")
    p.add_argument("--tp-dir", default=os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "TwoPuncturesC")))
    p.add_argument("--grid-n", type=int, default=61,
                   help="[uniform模式] 每方向网格点数(默认 61)")
    p.add_argument("--focus-n", type=int, default=201,
                   help="[adaptive模式] 奇点附近高分辨率块每方向点数(默认 201)")
    p.add_argument("--outer-n", type=int, default=61,
                   help="[adaptive模式] 外层低分辨率块每方向点数(默认 61)")
    p.add_argument("--focus-half", type=float, default=3.0,
                   help="[adaptive模式] 高分辨率块半边长(默认 3.0)")
    p.add_argument("--R", type=float, default=30.0)
    p.add_argument("--work-dir", default="tp_work")
    p.add_argument("--out", default="reference_u.npz")
    args = p.parse_args()

    os.makedirs(args.work_dir, exist_ok=True)
    bb = BBHConfig.from_case(args.case)
    xp = bb.x_plus[0]

    # ---- 1. par 文件 ----
    parfile = os.path.join(args.work_dir, f"{args.case}.par")
    write_parfile(bb, parfile)

    # ---- 2. 编译 ----
    dump_exe = compile_twopunctures(args.tp_dir, args.work_dir)

    # ---- 3. 生成网格块参数 ----
    if args.mode == "adaptive":
        blocks = adaptive_blocks(args.R, xp, args.focus_half,
                                 args.focus_n, args.outer_n)
        # 预估总点数
        inner_pts = 2 * args.focus_n ** 3  # 两个内层块
        outer_pts = args.outer_n ** 3       # 一个外层块
        print(f"[3/4] 自适应网格: {len(blocks)} 个块")
        print(f"  内层: 2×({args.focus_n}³) ≈ {inner_pts//1000}k 点 "
              f"(半宽={args.focus_half}, 步长≈{2*args.focus_half/(args.focus_n-1):.3f})")
        print(f"  外层: 1×({args.outer_n}³) ≈ {outer_pts//1000}k 点 "
              f"(步长≈{2*args.R/(args.outer_n-1):.3f})")
        print(f"  总计(重叠前去重): ≈ {(inner_pts+outer_pts)//1000}k 点")
    else:
        blocks = uniform_blocks(args.R, args.grid_n)
        print(f"[3/4] 均匀网格: {args.grid_n}³ ≈ {args.grid_n**3//1000}k 点")

    # ---- 3b. 运行 dump_psi_grid(自适应模式) ----
    psi_txt = os.path.join(args.work_dir, f"{args.case}_psi.txt")

    # 构建命令行参数
    cmd = [dump_exe, "--adaptive", parfile, str(xp), psi_txt]
    for blk in blocks:
        cmd.extend([str(v) for v in blk])

    print(f"[3/4] 运行 dump_psi_grid(自适应模式, {len(blocks)} 个块)...")
    run_streaming(cmd, "dump_psi_grid 运行失败")

    # ---- 4. 换算 u = ψ − 1 − Σ m/(2r), 去重并保存 npz ----
    print(f"[4/4] 换算修正项 u 并保存 {args.out}...")
    arr = np.loadtxt(psi_txt)                          # (M,4): x y z psi

    # ---- 去重:多个块可能重叠,保留首次出现的点(高分辨率块在前) ----
    # 使用坐标哈希去重(容忍浮点误差 ~1e-6)
    coords = arr[:, :3]
    # 量化到 1e-6 精度做去重键
    key = np.round(coords / 1e-6).astype(np.int64)
    _, unique_idx = np.unique(key, axis=0, return_index=True)
    unique_idx.sort()  # 保持首次出现的顺序
    arr = arr[unique_idx]

    x_ref = arr[:, :3].astype(np.float32)
    psi = arr[:, 3]
    r1 = np.linalg.norm(x_ref - np.array([xp, 0, 0]), axis=1)
    r2 = np.linalg.norm(x_ref - np.array([-xp, 0, 0]), axis=1)
    u_ref = (psi - 1.0 - bb.m_plus / (2.0 * r1) - bb.m_minus / (2.0 * r2)).astype(np.float32)

    np.savez(args.out, x_ref=x_ref, u_ref=u_ref)
    print(f"完成: {args.out} ({x_ref.shape[0]} 点, 去重后)")
    print(f"  u_ref 范围: [{u_ref.min():.4e}, {u_ref.max():.4e}]")
    print(f"  评估命令: python main.py --case {args.case} --reference {args.out}")


if __name__ == "__main__":
    main()