"""
validate_with_tp.py —— 用现成 TwoPunctures (Ansorg+2004, Einstein Toolkit 官方) 交叉验证自研谱求解器
====================================================================================================

原理:
    TwoPunctures 与 paper/tools/spectral_reference.py 解**同一个**哈密顿约束方程
    (Bowen-York puncture, ψ = 1 + Σm/2r + u), 但基函数完全不同
    (TP: 单域紧化 (A,B,φ) 谱 + Newton; 自研: (r,θ,φ) 球谐×逐 l Chebyshev 径向 LU)。
    逐点对比两者 u 即为独立交叉验证。

配置:
    a2_q20   : A2 非等质量 q=2 (m+=0.5@+3, m-=1.0@-3, P=(0,±0.2,0), S=0)
               vs paper/tools/refs_a2/ref_a2_q20.npz
    a3_0164  : A3 train_0164 (非等质量+自旋, 参数从 runs/multi_param_v5/configs.json 读取)
               vs paper/tools/refs/ref_train_0164.npz
    平移不变性处理: TP 强制奇点位于 x'=±par_b; A3 配置 x+≠|x-| 时,
    取 b=(x+-x-)/2, c=(x++x-)/2, 在 TP 坐标 x'=x-c 求解; 对比时把自研解
    在 x=x'+c 处求值 (椭圆方程与 BY 源均平移不变, 严格等价)。

运行前提:
    - WSL Ubuntu-24.04 已装 libgsl-dev, TwoPuncturesC 已 make, dump_psi_grid 已编译
      (编译命令见 paper/tools/solver_cross_validation.md)
    - 本机 venv 有 torch/numpy (评估自研解)

用法:
    .venv/Scripts/python.exe -u paper/tools/validate_with_tp.py            # 全部
    ... --labels a2_q20 --npoints 60 96                                    # 选择
输出:
    paper/tools/tp_work/<label>_n<np>.par / .psi
    paper/tools/tp_work/tp_vs_ours.json (逐配置指标) + 控制台汇总
"""

import argparse, json, os, re, subprocess, sys, time
import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # paper/
WSL_TP = "/mnt/d/AIs/PINN/TwoPuncturesC"
WSL_WORK = "/mnt/d/AIs/PINN/paper/tools/tp_work"
WIN_WORK = os.path.join(HERE, "tp_work")
WSL = ["wsl", "-d", "Ubuntu-24.04", "--"]

# a3_0164 的参数在运行时从 configs.json 读取, 避免硬编码
def load_a3_raw(label="train_0164"):
    cfg = json.load(open(os.path.join(ROOT, "runs", "multi_param_v5", "configs.json")))
    for e in cfg["train"]:
        if e["label"] == label:
            # 必须转成 python float: np.float64 的 repr 是 "np.float64(...)",
            # 写进 par 文件后 TP 解析不出(静默变成 0 → NaN → 断言崩溃)
            return [float(v) for v in np.array(e["raw"], dtype=float)]
    raise KeyError(label)

def a2_q20():
    return dict(m=[0.5, 1.0], xs=[[3.0, 0, 0], [-3.0, 0, 0]],
                Ps=[[0, 0.2, 0], [0, -0.2, 0]], Ss=[[0, 0, 0], [0, 0, 0]],
                ref=os.path.join(ROOT, "tools", "refs_a2", "ref_a2_q20.npz"))

def a3_0164():
    raw = load_a3_raw("train_0164")
    m = [float(raw[0]), float(raw[1])]
    xs = [[float(raw[2]), 0, 0], [float(raw[3]), 0, 0]]
    Ps = [[0, float(raw[4]), 0], [0, float(raw[5]), 0]]
    Ss = [[0, 0, float(raw[6])], [0, 0, float(raw[7])]]
    return dict(m=m, xs=xs, Ps=Ps, Ss=Ss,
                ref=os.path.join(ROOT, "tools", "refs", "ref_train_0164.npz"))

CONFIGS = {"a2_q20": a2_q20, "a3_0164": a3_0164}


def centered(cfg):
    """返回 (b, c): TP 在 x'=x-c 中求解, 奇点位于 x'=±b。"""
    xp, xm = cfg["xs"][0][0], cfg["xs"][1][0]
    return (xp - xm) / 2.0, (xp + xm) / 2.0


def write_par(cfg, b, npoints, path):
    (Pp, Pm), (Sp, Sm) = cfg["Ps"], cfg["Ss"]
    par = f"""# TwoPunctures par file generated by validate_with_tp.py
par_b={b!r}
par_m_plus={cfg['m'][0]!r}
par_m_minus={cfg['m'][1]!r}
target_M_plus=0.5
target_M_minus=0.5
par_P_plus1={Pp[0]}
par_P_plus2={Pp[1]}
par_P_plus3={Pp[2]}
par_P_minus1={Pm[0]}
par_P_minus2={Pm[1]}
par_P_minus3={Pm[2]}
par_S_plus1={Sp[0]}
par_S_plus2={Sp[1]}
par_S_plus3={Sp[2]}
par_S_minus1={Sm[0]}
par_S_minus2={Sm[1]}
par_S_minus3={Sm[2]}
center_offset1=0.
center_offset2=0.
center_offset3=0.
give_bare_mass=1
npoints_A={npoints}
npoints_B={npoints}
npoints_phi={npoints}
Newton_tol=1.0000000000000000e-10
Newton_maxit=5
TP_epsilon=0.
TP_Tiny=0.
TP_Extend_Radius=0.
adm_tol=1.0000000000000000e-10
solve_momentum_constraint=0
use_external_initial_guess=0
do_residuum_debug_output=0
do_initial_debug_output=0
do_solution_file_output=0
do_bam_file_output=0
grid_setup_method=0
initial_lapse=2
initial_lapse_psi_exponent=-2.0000000000000000e+00
conformal_state=1
swap_xz=0
multiply_old_lapse=0
verbose=1
"""
    with open(path, "w") as f:
        f.write(par)


def blocks_args(b):
    """四个网格块: 两个奇点邻域(±b±1.5, 121³, 步长0.025) + x 轴薄板(321×5×5, 含轴上精确行) + 外层(±31, 61³)。"""
    a = []
    for s in (+1.0, -1.0):
        a += [f"{s*b-1.5:.6f}", f"{s*b+1.5:.6f}", "-1.5", "1.5", "-1.5", "1.5",
              "121", "121", "121"]
    a += [f"{-(b+8):.6f}", f"{b+8:.6f}", "-0.06", "0.06", "-0.06", "0.06",
          "321", "5", "5"]
    a += ["-31", "31", "-31", "31", "-31", "31", "61", "61", "61"]
    return a


def run_tp(label, npoints, b):
    par_win = os.path.join(WIN_WORK, f"{label}_n{npoints}.par")
    psi_win = os.path.join(WIN_WORK, f"{label}_n{npoints}.psi")
    write_par_from_cfg(label, b, npoints, par_win)
    # WSL 路径必须用正斜杠手工拼接(os.path.join 在 Windows 会插入反斜杠,
    # 传进 Linux 后成为文件名字符 → 静默打开失败)
    par_wsl = f"{WSL_WORK}/{label}_n{npoints}.par"
    psi_wsl = f"{WSL_WORK}/{label}_n{npoints}.psi"
    exe_wsl = f"{WSL_WORK}/dump_psi_grid"
    cmd = WSL + [exe_wsl, "--adaptive", par_wsl, f"{b:.6f}", psi_wsl] + blocks_args(b)
    t0 = time.time()
    r = subprocess.run(cmd, capture_output=True, text=True)
    log = r.stdout + r.stderr
    adm = re.findall(r"ADM [Mm]ass[^\n]*", log)
    print(f"[TP] {label} n={npoints}: rc={r.returncode}, {time.time()-t0:.0f}s"
          + (f"; {adm}" if adm else ""), flush=True)
    if r.returncode != 0 or not os.path.exists(psi_win):
        print(log[-3000:], flush=True)
        raise RuntimeError(f"TP run failed or no output: {label} n={npoints}")
    with open(os.path.join(WIN_WORK, f"{label}_n{npoints}.log"), "w", encoding="utf-8", errors="replace") as f:
        f.write(log)
    return psi_win, adm


def write_par_from_cfg(label, b, npoints, path):
    cfg = CONFIGS[label]()
    write_par(cfg, b, npoints, path)


def load_psi(path):
    try:
        import pandas as pd
        df = pd.read_csv(path, sep=r"\s+", header=None, names=["x", "y", "z", "psi"])
        return df.to_numpy()
    except ImportError:
        return np.loadtxt(path)


def compare(label, npoints, b, c, device):
    cfg = CONFIGS[label]()
    m1, m2 = cfg["m"]
    x1, x2 = cfg["xs"][0], cfg["xs"][1]
    arr = load_psi(os.path.join(WIN_WORK, f"{label}_n{npoints}.psi"))
    # 完整性: 以 TP 日志自报的 "Total written" 为准(块间重叠会被去重),
    # 防止中止/截断的 psi 被静默对比
    log_path = os.path.join(WIN_WORK, f"{label}_n{npoints}.live.log")
    m = re.search(r"Total written: (\d+) grid points", open(log_path, encoding="utf-8", errors="replace").read())
    if not m:
        raise RuntimeError(f"{label} n={npoints}: live.log 无 'Total written'(求解未完成?)")
    expected = int(m.group(1))
    if arr.shape[0] != expected:
        raise RuntimeError(f"{label} n={npoints}: psi 点数 {arr.shape[0]} != 日志报告 {expected}"
                           "(求解被中止或截断?)")
    xp_tp, yp_tp, zp_tp, psi = arr[:, 0], arr[:, 1], arr[:, 2], arr[:, 3]
    # TP 坐标 x' → 我们的坐标 x = x' + c
    x_o = xp_tp + c
    pts = np.stack([x_o, yp_tp, zp_tp], axis=1)
    r1 = np.linalg.norm(pts - np.array(x1), axis=1)
    r2 = np.linalg.norm(pts - np.array(x2), axis=1)
    rmin = np.minimum(r1, r2)
    keep = rmin > 0.05
    psi, pts, rmin, r1, r2 = psi[keep], pts[keep], rmin[keep], r1[keep], r2[keep]
    u_tp = psi - 1.0 - m1 / (2 * r1) - m2 / (2 * r2)

    from spectral_reference import SpectralPunctureSolver
    ev = SpectralPunctureSolver.from_coefficients(cfg["ref"], device=device, verify=False)
    u_ours = ev.evaluate(pts, chunk=16384, dtype=torch.float64).astype(float)

    d = u_ours - u_tp
    def l2re(mask=None):
        if mask is None:
            num, den = d, u_tp
        else:
            num, den = d[mask], u_tp[mask]
        return float(np.sqrt(np.sum(num**2) / max(np.sum(den**2), 1e-300)))
    reg = {
        "r<0.5": rmin < 0.5, "0.5-2": (rmin >= 0.5) & (rmin < 2),
        "2-10": (rmin >= 2) & (rmin < 10), ">10": rmin >= 10,
        "axis(y=z=0)": (np.abs(pts[:, 1]) < 1e-9) & (np.abs(pts[:, 2]) < 1e-9),
    }
    out = {
        "n_points": int(len(d)), "L2RE_all": l2re(),
        "regions": {k: l2re(m) for k, m in reg.items() if m.any()},
        "max_abs_diff": float(np.max(np.abs(d))),
        "median_abs_diff": float(np.median(np.abs(d))),
    }
    print(f"[CMP] {label} n={npoints}: L2RE_all={out['L2RE_all']:.3e}  "
          + "  ".join(f"{k}={v:.3e}" for k, v in out["regions"].items()), flush=True)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--labels", default="a2_q20,a3_0164")
    ap.add_argument("--npoints", type=int, nargs="+", default=[60, 96])
    args = ap.parse_args()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(WIN_WORK, exist_ok=True)
    report = {}
    for label in args.labels.split(","):
        cfg = CONFIGS[label]()
        b, c = centered(cfg)
        per = {}
        for np_ in args.npoints:
            run_tp(label, np_, b)
            per[f"n{np_}"] = compare(label, np_, b, c, device)
        if len(args.npoints) > 1:
            n1, n2 = [f"n{n_}" for n_ in args.npoints[:2]]
            per["tp_selfconv_L2RE"] = "见 tp_vs_ours.json (n60 vs n96 同网格逐点)"
        report[label] = per
        json.dump(report, open(os.path.join(WIN_WORK, "tp_vs_ours.json"), "w"), indent=2)
    print("DONE ->", os.path.join(WIN_WORK, "tp_vs_ours.json"), flush=True)


if __name__ == "__main__":
    main()
